name: My Workflow
on: workflow_dispatch
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo 'Hello world'
      - name: Print good bye
        run: echo 'good bye'
  SecondJob:
    runs-on: ubuntu-latest
    steps:
      - name: do calc
      - run: echo "3 + 5" | bc
