name: Second Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: sample add
        run: |
          echo "3 + 5" | bc
          echo "3 * 5" | bc
  secondjob:
    runs-on: ubuntu-latest 
    steps:
      - name: simple min
        run: echo "5 - 3" | bc
      
